name: peqod

services:
  peqod-db:
    container_name: peqod-db
    image: mysql:5.7
    platform: linux/amd64
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--innodb_use_native_aio=0']
    ports:
      - '3306:3306'
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: 'cu-graph-db'
      MYSQL_USER: 'cu-graph-user'
      MYSQL_PASSWORD: 'password1'
      MYSQL_ROOT_PASSWORD: 'password2'
    volumes:
      - /Users/soid/.peqod/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword2"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  peqod-cache:
    container_name: peqod-cache
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  peqod-web:
    container_name: peqod-web
    build: .
    command: python catalog/manage.py runserver --insecure 0.0.0.0:8002
    environment:
      - PEQOD_DEBUG=True
      - PEQOD_MYSQL_HOST=peqod-db
      - PEQOD_MYSQL_NAME=cu-graph-db
      - PEQOD_MYSQL_USER=root
      - PEQOD_MYSQL_PW=password2
      - PEQOD_MEMCACHE_LOCATION=peqod-cache:11211
      - PEQOD_SENTRY_DSN=${PEQOD_SENTRY_DSN:-}
    volumes:
      - .:/CUGraphWeb
      - /Users/soid/Dropbox/Code/2020/columbia-catalog-data:/columbia-catalog-data
    ports:
      - "8000:8002"
    depends_on:
      peqod-db:
        condition: service_healthy
