# Generated by Django 3.2 on 2021-05-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.CharField(max_length=6)),
                ('call_number', models.IntegerField()),
                ('class_id', models.CharField(max_length=24)),
                ('section_key', models.CharField(max_length=24)),
                ('course_code', models.CharField(max_length=16)),
                ('course_title', models.CharField(max_length=128)),
                ('course_subtitle', models.CharField(max_length=128)),
                ('course_descr', models.TextField()),
                ('instructor', models.CharField(max_length=128)),
                ('instructor_culpa_link', models.URLField()),
                ('instructor_culpa_reviews_count', models.PositiveSmallIntegerField()),
                ('instructor_wikipedia_link', models.URLField()),
                ('link', models.URLField()),
                ('department', models.CharField(max_length=128)),
                ('department_code', models.CharField(max_length=12)),
                ('scheduled_time_start', models.TimeField()),
                ('scheduled_time_end', models.TimeField()),
                ('scheduled_days', models.CharField(max_length=7)),
                ('location', models.CharField(max_length=128)),
                ('points', models.PositiveSmallIntegerField()),
                ('added_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
