# Generated by Django 3.2 on 2021-05-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('courses', '0001_initial'), ('courses', '0002_auto_20210505_0359'), ('courses', '0003_auto_20210505_0411'), ('courses', '0004_alter_course_points'), ('courses', '0005_alter_course_points'), ('courses', '0006_alter_course_points'), ('courses', '0007_alter_course_points')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.CharField(max_length=6)),
                ('call_number', models.IntegerField()),
                ('class_id', models.CharField(max_length=24)),
                ('section_key', models.CharField(max_length=24)),
                ('course_code', models.CharField(max_length=16)),
                ('course_title', models.CharField(max_length=128)),
                ('course_subtitle', models.CharField(max_length=128, null=True)),
                ('course_descr', models.TextField(null=True)),
                ('instructor', models.CharField(max_length=128, null=True)),
                ('instructor_culpa_link', models.URLField(null=True)),
                ('instructor_culpa_reviews_count', models.PositiveSmallIntegerField(null=True)),
                ('instructor_wikipedia_link', models.URLField(null=True)),
                ('link', models.URLField(null=True)),
                ('department', models.CharField(max_length=128)),
                ('department_code', models.CharField(max_length=12)),
                ('scheduled_time_start', models.TimeField(null=True)),
                ('scheduled_time_end', models.TimeField(null=True)),
                ('scheduled_days', models.CharField(max_length=7, null=True)),
                ('location', models.CharField(max_length=128, null=True)),
                ('points', models.PositiveSmallIntegerField()),
                ('added_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('year', 'semester', 'call_number'), name='class per semester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='course',
            name='points',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='points',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='points',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='points',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='points',
            field=models.CharField(max_length=6),
        ),
    ]
