# Generated by Django 3.2 on 2021-08-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210514_2039_squashed_0007_course_semester_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='points',
            field=models.CharField(max_length=7),
        ),
    ]
