# Generated by Django 3.2 on 2021-08-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=12)),
                ('last_modified_date', models.DateTimeField()),
            ],
        ),
    ]
