# Generated by Django 3.2 on 2021-08-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('courses', '0005_course_courses_cou_departm_9688c2_idx'), ('courses', '0006_course_courses_cou_added_d_d80881_idx'), ('courses', '0007_course_courses_cou_departm_db05ab_idx'), ('courses', '0008_catalogupdate_courses_cat_added_d_28dc8f_idx'), ('courses', '0009_course_courses_cou_course__0d2ddc_idx'), ('courses', '0010_instructor_courses_ins_name_393055_idx'), ('courses', '0011_course_courses_cou_instruc_d2e347_idx')]

    dependencies = [
        ('courses', '0004_catalogimports'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department'], name='courses_cou_departm_9688c2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['added_date'], name='courses_cou_added_d_d80881_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'year', 'semester'], name='courses_cou_departm_db05ab_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogupdate',
            index=models.Index(fields=['added_date'], name='courses_cat_added_d_28dc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code', 'year', 'semester'], name='courses_cou_course__0d2ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['name'], name='courses_ins_name_393055_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='courses_cou_instruc_d2e347_idx'),
        ),
    ]
