# Generated by Django 3.2 on 2021-08-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210824_2038'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['call_number', 'year', 'semester'], name='courses_cou_call_nu_e9d65e_idx'),
        ),
    ]
