# Generated by Django 3.2 on 2021-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_courses_cou_call_nu_e9d65e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogupdate',
            name='department',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
