# Generated by Django 3.2 on 2021-09-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_catalogupdate_department'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='catalogupdate',
            index=models.Index(fields=['department'], name='courses_cat_departm_d05385_idx'),
        ),
    ]
