# Generated by Django 3.2 on 2021-10-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_catalogupdate_courses_cat_departm_d05385_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='great_teacher_award',
            field=models.PositiveSmallIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='gscholar_hindex',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='gscholar_hindex5y',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='gscholar_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='gscholar_json',
            field=models.JSONField(null=True),
        ),
    ]
