# Generated by Django 3.2 on 2021-11-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20211010_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='great_teacher_award',
            field=models.PositiveSmallIntegerField(default=False),
        ),
    ]
