# Generated by Django 3.2 on 2021-11-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20211101_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_cur',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_max',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
