# Generated by Django 3.2 on 2021-11-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20211112_1817'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_instruc_d2e347_idx',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['scheduled_time_start'], name='courses_cou_schedul_195f07_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['scheduled_time_end'], name='courses_cou_schedul_b4caa3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['scheduled_days'], name='courses_cou_schedul_dc45a5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['points_min'], name='courses_cou_points__3aa3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['points_max'], name='courses_cou_points__2007bb_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['enrollment_cur'], name='courses_cou_enrollm_5c6b74_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['enrollment_max'], name='courses_cou_enrollm_c8ebc4_idx'),
        ),
    ]
